"""Add composite indexes to Post model

Revision ID: 53e8b2ebb360
Revises: b6d018b18ee6
Create Date: 2026-06-03 17:05:35.756639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e8b2ebb360'
down_revision: Union[str, Sequence[str], None] = 'b6d018b18ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
