"""add post_type and disclosure_tag to posts

Revision ID: a46fa57c8b16
Revises: 3ba19333fd68
Create Date: 2026-05-30 16:02:04.283970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a46fa57c8b16'
down_revision: Union[str, Sequence[str], None] = '3ba19333fd68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_type', sa.String(length=20), nullable=True))
    op.add_column('posts', sa.Column('disclosure_tag', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_posts_post_type'), 'posts', ['post_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_post_type'), table_name='posts')
    op.drop_column('posts', 'disclosure_tag')
    op.drop_column('posts', 'post_type')
    # ### end Alembic commands ###
